export const testQuestionForSinglePage = [
  {
    id: "hff45wb1",
    title: "請用一句話描述自己",
    note: "",
    page: 1,
    type: "0",
    validations: {
      required: true,
      length: 50,
    },
  },
  {
    id: "wet65121",
    title: "為什麼想想這篇文章呢",
    note: "",
    page: 1,
    type: "1",
    validations: {
      required: false,
      length: 200,
    },
  },
  {
    id: "15thghls",
    title: "下面將會有更多題目!",
    note: "",
    page: 1,
    type: "2",
    validations: {
      required: false,
      length: 200,
    },
  },
  {
    id: "n4pyu1pl",
    title: "你最喜歡的語言?",
    note: "",
    page: 1,
    type: "3",
    options: [
      "夜光閃亮亮復仇鬼之JavaScript",
      "無所不用其及防禦的TypeScript",
      "趴倒好像每個商科學生都要會的Python",
    ],
    validations: {
      required: true,
      maxSelected: 1,
    },
  },
  {
    id: "gfhk78re",
    title: "如果可以，想喝的飲料在這裡?",
    note: "",
    page: 1,
    type: "4",
    options: ["可不可-雪藏紅茶", "五桐號-手沖泰奶", "曼士茶-泰奶可可碎片", "COCO-奶茶三兄弟"],
    validations: {
      required: false,
      maxSelected: 2,
    },
  },
  {
    id: "4sjm5tls",
    title: "下面將會有更多題目!",
    note: "",
    page: 1,
    type: "2",
    validations: {
      required: false,
      length: 200,
    },
  },
  {
    id: "agk1lf45",
    title: "滿意程度來一下?",
    note: "",
    page: 1,
    type: "5",
    options: ["可不可-雪藏紅茶", "五桐號-手沖泰奶", "曼士茶-泰奶可可碎片", "COCO-奶茶三兄弟"],
    matrixs: ["很愛", "再看看", "別出現"],
    validations: {
      required: false,
      maxSelected: 1,
    },
  },
  {
    id: "4mq44wb7",
    title: "好多題目，猜猜總共幾題?",
    note: "",
    page: 1,
    type: "6",
    validations: {
      required: false,
      max: 100,
      min: 1,
      unit: "",
      interval: 1,
    },
  },
  {
    id: "15qwklk1",
    title: "一個滑桿，各自表述",
    note: "",
    page: 1,
    type: "7",
    validations: {
      required: false,
      min: 1,
      max: 100,
      unit: "",
      interval: 1,
    },
  },
  {
    id: "5goihkwq",
    title: "排序排序ψ(｀∇´)ψ",
    note: "三個都要排~",
    page: 1,
    type: "8",
    options: ["立頓鮮奶茶", "飲冰室茶集奶茶", "義美紅茶配牛奶"],
    validations: {
      required: true,
      maxSelected: 3,
    },
  },
  {
    id: "7klei4sq",
    title: "可以填個生日，或你看最順眼的日子",
    note: "亂點一個也沒關係!",
    page: 1,
    type: "9",
    validations: {
      required: false,
      multipleDate: false,
      hasRange: false,
      startDate: null,
      endDate: null,
      maxSelectedDateQuantity: null,
    },
  },
];

export const testQuestionForMultiplePage = [
  {
    id: "hff45wb1",
    title: "請用一句話描述自己",
    note: "",
    page: 1,
    type: "0",
    validations: {
      required: true,
      length: 50,
    },
  },
  {
    id: "wet65121",
    title: "為什麼想想這篇文章呢",
    note: "",
    page: 1,
    type: "1",
    validations: {
      required: false,
      length: 200,
    },
  },
  {
    id: "15thghls",
    title: "下頁將會有更多題目!",
    note: "",
    page: 1,
    type: "2",
    validations: {
      required: false,
      length: 200,
    },
  },
  {
    id: "n4pyu1pl",
    title: "你最喜歡的語言?",
    note: "",
    page: 2,
    type: "3",
    options: [
      "夜光閃亮亮復仇鬼之JavaScript",
      "無所不用其及防禦的TypeScript",
      "趴倒好像每個商科學生都要會的Python",
    ],
    validations: {
      required: true,
      maxSelected: 1,
    },
  },
  {
    id: "gfhk78re",
    title: "如果可以，想喝的飲料在這裡?",
    note: "",
    page: 2,
    type: "4",
    options: ["可不可-雪藏紅茶", "五桐號-手沖泰奶", "曼士茶-泰奶可可碎片", "COCO-奶茶三兄弟"],
    validations: {
      required: false,
      maxSelected: 2,
    },
  },
  {
    id: "4sjm5tls",
    title: "下頁將會有更多題目!",
    note: "",
    page: 2,
    type: "2",
    validations: {
      required: false,
      length: 200,
    },
  },
  {
    id: "agk1lf45",
    title: "滿意程度來一下?",
    note: "",
    page: 3,
    type: "5",
    options: ["可不可-雪藏紅茶", "五桐號-手沖泰奶", "曼士茶-泰奶可可碎片", "COCO-奶茶三兄弟"],
    matrixs: ["很愛", "再看看", "別出現"],
    validations: {
      required: false,
      maxSelected: 1,
    },
  },
  {
    id: "4mq44wb7",
    title: "好多題目，猜猜總共幾題?",
    note: "",
    page: 3,
    type: "6",
    validations: {
      required: false,
      max: 100,
      min: 1,
      unit: "",
      interval: 1,
    },
  },
  {
    id: "15qwklk1",
    title: "一個滑桿，各自表述",
    note: "",
    page: 3,
    type: "7",
    validations: {
      required: false,
      min: 1,
      max: 100,
      unit: "",
      interval: 1,
    },
  },
  {
    id: "5goihkwq",
    title: "排序排序ψ(｀∇´)ψ",
    note: "三個都要排~",
    page: 3,
    type: "8",
    options: ["立頓鮮奶茶", "飲冰室茶集奶茶", "義美紅茶配牛奶"],
    validations: {
      required: true,
      maxSelected: 3,
    },
  },
  {
    id: "7klei4sq",
    title: "可以填個生日，或你看最順眼的日子",
    note: "亂點一個也沒關係!",
    page: 3,
    type: "9",
    validations: {
      required: false,
      multipleDate: false,
      hasRange: false,
      startDate: null,
      endDate: null,
      maxSelectedDateQuantity: null,
    },
  },
];
export const pageQuantity = 3;
export const testQuantityInDifferentPage = [3, 3, 5];
export const testIndexsForOnePageMode = ["1", "2", "", "3", "4", "", "5", "6", "7", "8", "9"];
export const testIntervalPoints = [0, 3, 6, 11];
export const testConfigObject = {
  THEME1_COLOR: "main",
  THEME2_COLOR: "yellow",
  THEME3_COLOR: "green",
  FONT1_CODE: "0",
  FONT2_CODE: "1",
  FONT3_CODE: "2",
};
